//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Areas
    {
        public int Id { get; set; }
        public string Proyecto { get; set; }
        public string NombreObra { get; set; }
        public string CodigoObraInmueble { get; set; }
        public string CodigoBloque { get; set; }
        public string NombreManzana { get; set; }
        public string CodigoInmueble { get; set; }
        public Nullable<decimal> ValorVenta { get; set; }
        public Nullable<decimal> Area { get; set; }
    }
}
