//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClasificacionPresupuestos
    {
        public int Id { get; set; }
        public string CodPresu { get; set; }
        public string NomPresu { get; set; }
        public Nullable<int> Tipo { get; set; }
    }
}
