//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostoEntrado
    {
        public int Id { get; set; }
        public string referencia1 { get; set; }
        public string nombppto { get; set; }
        public string fecha { get; set; }
        public string orden { get; set; }
        public string Nliqu { get; set; }
        public string codterc { get; set; }
        public string nombre { get; set; }
        public string cap { get; set; }
        public string nombrecap { get; set; }
        public string apu { get; set; }
        public string nombapu { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public string unidad { get; set; }
        public Nullable<decimal> cantent { get; set; }
        public Nullable<decimal> vlrunitentrado { get; set; }
        public Nullable<decimal> costoentrado1 { get; set; }
        public string usuario { get; set; }
        public Nullable<int> IdFecha { get; set; }
    
        public virtual Fechas Fechas { get; set; }
    }
}
