//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostosPptoProg
    {
        public int Id { get; set; }
        public string referencia1 { get; set; }
        public string referencia2 { get; set; }
        public string referencia3 { get; set; }
        public string presupuesto { get; set; }
        public string codcapi { get; set; }
        public string capitulo { get; set; }
        public string codunit { get; set; }
        public string unitario { get; set; }
        public string undunita { get; set; }
        public Nullable<decimal> cantxppto { get; set; }
        public string codinsu { get; set; }
        public string insutipo { get; set; }
        public string insumo { get; set; }
        public string unidinsu { get; set; }
        public string ctrlinven { get; set; }
        public string validación { get; set; }
        public Nullable<decimal> precioppto { get; set; }
        public Nullable<decimal> consumounitario { get; set; }
        public Nullable<decimal> consumototal { get; set; }
        public Nullable<decimal> adic { get; set; }
        public Nullable<decimal> precioaut { get; set; }
        public Nullable<decimal> preciocompra { get; set; }
        public Nullable<decimal> precioentrado { get; set; }
        public Nullable<decimal> ped { get; set; }
        public Nullable<decimal> aprob { get; set; }
        public Nullable<decimal> comp { get; set; }
        public Nullable<decimal> ent { get; set; }
        public Nullable<decimal> sali { get; set; }
        public Nullable<decimal> traslado { get; set; }
        public Nullable<decimal> xcomp { get; set; }
        public Nullable<decimal> xent { get; set; }
        public Nullable<decimal> saldoxunit { get; set; }
        public Nullable<decimal> saldoxppto { get; set; }
        public Nullable<decimal> vlrent { get; set; }
        public Nullable<decimal> vlrenttraslado { get; set; }
        public Nullable<decimal> vlrcompradoxent { get; set; }
        public Nullable<decimal> vlrxcomp { get; set; }
        public Nullable<decimal> vlrtraslado { get; set; }
        public Nullable<decimal> vlrproy { get; set; }
        public Nullable<decimal> vlrproyejec { get; set; }
        public Nullable<decimal> vlrini { get; set; }
        public Nullable<decimal> vlrejec { get; set; }
        public Nullable<int> IdFecha { get; set; }
        public Nullable<decimal> descuento { get; set; }
    
        public virtual Fechas Fechas { get; set; }
    }
}
