//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descuentos
    {
        public int Id { get; set; }
        public string Referencia { get; set; }
        public string Tercero { get; set; }
        public string Liquidacion { get; set; }
        public string Obra { get; set; }
        public string Concepto { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Presupuesto { get; set; }
        public Nullable<int> IdFecha { get; set; }
    }
}
