//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyectos
    {
        public Proyectos()
        {
            this.Fechas = new HashSet<Fechas>();
        }
    
        public string Codigo { get; set; }
        public string Proyecto { get; set; }
        public string Filtro { get; set; }
        public Nullable<System.DateTime> FechaIniObra { get; set; }
        public Nullable<System.DateTime> FechaFinObra { get; set; }
    
        public virtual ICollection<Fechas> Fechas { get; set; }
    }
}
