//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salidas
    {
        public int Id { get; set; }
        public string referencia { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string liquidacion { get; set; }
        public string valeconsumo { get; set; }
        public string salida { get; set; }
        public string tiposa { get; set; }
        public string codcapi { get; set; }
        public string codunita { get; set; }
        public string codinsum { get; set; }
        public string insumo { get; set; }
        public Nullable<decimal> cant { get; set; }
        public Nullable<decimal> costsali { get; set; }
        public string saliobse { get; set; }
        public string saliusua { get; set; }
        public Nullable<int> IdFecha { get; set; }
    
        public virtual Fechas Fechas { get; set; }
    }
}
