//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaCostos
    {
        public string Referencia1 { get; set; }
        public string presupuesto { get; set; }
        public Nullable<decimal> Vlrproy { get; set; }
        public Nullable<decimal> Vlrejecutado { get; set; }
        public Nullable<decimal> VlrCausado { get; set; }
        public Nullable<int> IdFecha { get; set; }
        public int Clasificacion { get; set; }
        public string nombreclasi { get; set; }
    }
}
